// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gofiber/fiber/v2"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for PaymentStatus.
const (
	PaymentStatusCompleted PaymentStatus = "completed"
	PaymentStatusFailed    PaymentStatus = "failed"
	PaymentStatusPending   PaymentStatus = "pending"
)

// Defines values for QuestionType.
const (
	MultipleChoice QuestionType = "multiple_choice"
	Rating         QuestionType = "rating"
	Text           QuestionType = "text"
)

// Defines values for TransactionStatus.
const (
	TransactionStatusFailed  TransactionStatus = "failed"
	TransactionStatusPending TransactionStatus = "pending"
	TransactionStatusSuccess TransactionStatus = "success"
)

// Defines values for TransactionType.
const (
	TransactionTypeAirtime TransactionType = "airtime"
)

// Defines values for TransactionInputStatus.
const (
	TransactionInputStatusFailed  TransactionInputStatus = "failed"
	TransactionInputStatusPending TransactionInputStatus = "pending"
	TransactionInputStatusSuccess TransactionInputStatus = "success"
)

// Defines values for TransactionInputType.
const (
	TransactionInputTypeAirtime TransactionInputType = "airtime"
)

// Defines values for TransactionStatusUpdateStatus.
const (
	TransactionStatusUpdateStatusFailed     TransactionStatusUpdateStatus = "failed"
	TransactionStatusUpdateStatusPending    TransactionStatusUpdateStatus = "pending"
	TransactionStatusUpdateStatusSuccessful TransactionStatusUpdateStatus = "successful"
)

// Balance defines model for Balance.
type Balance struct {
	Amount          float32            `json:"amount"`
	CampaignId      openapi_types.UUID `json:"campaignId"`
	Id              openapi_types.UUID `json:"id"`
	StartingBalance float32            `json:"startingBalance"`
}

// Campaign defines model for Campaign.
type Campaign struct {
	Amount         float32            `json:"amount"`
	CampaignName   string             `json:"campaignName"`
	CharacterType  string             `json:"characterType"`
	CouponId       string             `json:"couponId"`
	CouponLength   int                `json:"couponLength"`
	CouponNumber   int                `json:"couponNumber"`
	CreatedAt      *time.Time         `json:"createdAt"`
	Id             openapi_types.UUID `json:"id"`
	OrganizationId openapi_types.UUID `json:"organizationId"`
	Price          float32            `json:"price"`
	QuestionNumber int                `json:"questionNumber"`
	Status         string             `json:"status"`
	WelcomeMessage string             `json:"welcomeMessage"`
}

// Coupon defines model for Coupon.
type Coupon struct {
	CampaignId openapi_types.UUID `json:"campaignId"`
	Code       string             `json:"code"`
	Id         openapi_types.UUID `json:"id"`
	Redeemed   bool               `json:"redeemed"`
	RedeemedAt *time.Time         `json:"redeemedAt"`
}

// CreateBalanceRequest defines model for CreateBalanceRequest.
type CreateBalanceRequest struct {
	Amount          float32            `json:"amount"`
	CampaignId      openapi_types.UUID `json:"campaignId"`
	StartingBalance float32            `json:"startingBalance"`
}

// CreateUserRequestBody defines model for CreateUserRequestBody.
type CreateUserRequestBody struct {
	Address         string              `json:"address"`
	ConfirmPassword string              `json:"confirmPassword"`
	Email           openapi_types.Email `json:"email"`
	FirstName       string              `json:"firstName"`
	LastName        string              `json:"lastName"`
	OrganizationId  openapi_types.UUID  `json:"organization_id"`
	Password        string              `json:"password"`
	PhoneNumber     string              `json:"phoneNumber"`
	Role            string              `json:"role"`
}

// Customer defines model for Customer.
type Customer struct {
	Amount         float32             `json:"amount"`
	CampaignId     openapi_types.UUID  `json:"campaignId"`
	Email          openapi_types.Email `json:"email"`
	Feedback       string              `json:"feedback"`
	FirstName      string              `json:"firstName"`
	Id             openapi_types.UUID  `json:"id"`
	LastName       string              `json:"lastName"`
	Network        string              `json:"network"`
	OrganizationId openapi_types.UUID  `json:"organizationId"`
	Phone          string              `json:"phone"`
	Status         string              `json:"status"`
}

// Error defines model for Error.
type Error struct {
	ErrorCode string `json:"error_code"`
	Message   string `json:"message"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// Organization defines model for Organization.
type Organization struct {
	Address            string              `json:"address"`
	CompanyName        string              `json:"company_name"`
	CompanySize        int                 `json:"company_size"`
	ContactPersonName  string              `json:"contact_person_name"`
	ContactPersonPhone string              `json:"contact_person_phone"`
	Email              openapi_types.Email `json:"email"`
	Id                 openapi_types.UUID  `json:"id"`
	Industry           string              `json:"industry"`
}

// Payment defines model for Payment.
type Payment struct {
	Amount         float32            `json:"amount"`
	CampaignId     openapi_types.UUID `json:"campaign_id"`
	Id             openapi_types.UUID `json:"id"`
	OrganizationId openapi_types.UUID `json:"organization_id"`
	Status         PaymentStatus      `json:"status"`
	TransactionId  string             `json:"transaction_id"`
	TransactionRef string             `json:"transaction_ref"`
}

// PaymentStatus defines model for Payment.Status.
type PaymentStatus string

// Question defines model for Question.
type Question struct {
	CampaignId openapi_types.UUID `json:"campaignId"`
	Id         openapi_types.UUID `json:"id"`
	Options    *[]string          `json:"options"`
	Text       string             `json:"text"`
	Type       QuestionType       `json:"type"`
}

// QuestionType defines model for Question.Type.
type QuestionType string

// Response defines model for Response.
type Response struct {
	Answer     string             `json:"answer"`
	CustomerId openapi_types.UUID `json:"customerId"`
	Id         openapi_types.UUID `json:"id"`
	QuestionId openapi_types.UUID `json:"questionId"`
}

// Transaction defines model for Transaction.
type Transaction struct {
	Amount         float32            `json:"amount"`
	CampaignId     openapi_types.UUID `json:"campaignId"`
	CustomerId     openapi_types.UUID `json:"customerId"`
	Id             openapi_types.UUID `json:"id"`
	Network        string             `json:"network"`
	OrganizationId openapi_types.UUID `json:"organizationId"`
	PhoneNumber    string             `json:"phoneNumber"`
	Reference      string             `json:"reference"`
	Status         TransactionStatus  `json:"status"`
	TxReference    string             `json:"txReference"`
	Type           TransactionType    `json:"type"`
}

// TransactionStatus defines model for Transaction.Status.
type TransactionStatus string

// TransactionType defines model for Transaction.Type.
type TransactionType string

// TransactionInput defines model for TransactionInput.
type TransactionInput struct {
	Amount         float32                `json:"amount"`
	CampaignId     openapi_types.UUID     `json:"campaignId"`
	Commisson      float32                `json:"commisson"`
	CustomerId     openapi_types.UUID     `json:"customerId"`
	Network        string                 `json:"network"`
	OrganizationId openapi_types.UUID     `json:"organizationId"`
	PhoneNumber    string                 `json:"phoneNumber"`
	Status         TransactionInputStatus `json:"status"`
	TxReference    string                 `json:"txReference"`
	Type           TransactionInputType   `json:"type"`
}

// TransactionInputStatus defines model for TransactionInput.Status.
type TransactionInputStatus string

// TransactionInputType defines model for TransactionInput.Type.
type TransactionInputType string

// TransactionStatusUpdate defines model for TransactionStatusUpdate.
type TransactionStatusUpdate struct {
	Status TransactionStatusUpdateStatus `json:"status"`
}

// TransactionStatusUpdateStatus defines model for TransactionStatusUpdate.Status.
type TransactionStatusUpdateStatus string

// UpdateBalanceRequest defines model for UpdateBalanceRequest.
type UpdateBalanceRequest struct {
	Amount float32 `json:"amount"`
}

// User defines model for User.
type User struct {
	Address        string              `json:"address"`
	Email          openapi_types.Email `json:"email"`
	Firstname      string              `json:"firstname"`
	Id             openapi_types.UUID  `json:"id"`
	Lastname       string              `json:"lastname"`
	OrganizationId openapi_types.UUID  `json:"organization_id"`
	Password       string              `json:"password"`
	Role           string              `json:"role"`
}

// BadRequestError defines model for BadRequestError.
type BadRequestError = Error

// InternalServerError defines model for InternalServerError.
type InternalServerError = Error

// NotFound defines model for NotFound.
type NotFound = Error

// GetAllBalancesParams defines parameters for GetAllBalances.
type GetAllBalancesParams struct {
	Limit  *int `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// GetAllCampaignsParams defines parameters for GetAllCampaigns.
type GetAllCampaignsParams struct {
	// Limit Number of campaigns to return (pagination)
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of campaigns to skip before starting to return results
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// GetCampaignsByOrganizationParams defines parameters for GetCampaignsByOrganization.
type GetCampaignsByOrganizationParams struct {
	// Limit Number of campaigns to return (pagination)
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of campaigns to skip before starting to return results
	Offset         *int               `form:"offset,omitempty" json:"offset,omitempty"`
	OrganizationId openapi_types.UUID `form:"organizationId" json:"organizationId"`
}

// GetCampaignsCampaignIdQuestionsParams defines parameters for GetCampaignsCampaignIdQuestions.
type GetCampaignsCampaignIdQuestionsParams struct {
	// Limit Number of questions to return (pagination)
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of questions to skip before starting to return results
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// PostCampaignsCampaignIdQuestionsJSONBody defines parameters for PostCampaignsCampaignIdQuestions.
type PostCampaignsCampaignIdQuestionsJSONBody = []Question

// GetAllCustomersParams defines parameters for GetAllCustomers.
type GetAllCustomersParams struct {
	// Limit Number of campaigns to return (pagination)
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of campaigns to skip before starting to return results
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// GetCustomersByOrganizationParams defines parameters for GetCustomersByOrganization.
type GetCustomersByOrganizationParams struct {
	OrganizationId openapi_types.UUID `form:"organizationId" json:"organizationId"`

	// Limit Number of customers to return (pagination)
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of customers to skip before starting to return results
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// PostFlutterwaveWebhookJSONBody defines parameters for PostFlutterwaveWebhook.
type PostFlutterwaveWebhookJSONBody struct {
	// Data Payload containing transaction details
	Data *struct {
		// Amount Amount involved in the transaction
		Amount *int `json:"amount,omitempty"`

		// Id Unique transaction ID
		Id *int `json:"id,omitempty"`

		// Status Transaction status (e.g., successful, failed)
		Status *string `json:"status,omitempty"`

		// TxRef Transaction reference
		TxRef *string `json:"tx_ref,omitempty"`
	} `json:"data,omitempty"`

	// Event Type of event (e.g., charge.completed, transfer.successful)
	Event *string `json:"event,omitempty"`
}

// GetOrganizationsParams defines parameters for GetOrganizations.
type GetOrganizationsParams struct {
	// Limit Number of organizations to return (pagination)
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of organizations to skip before starting to return results
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// GetOrganizationByNameParams defines parameters for GetOrganizationByName.
type GetOrganizationByNameParams struct {
	Name string `form:"name" json:"name"`

	// Limit Number of organizations to return (pagination)
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of organizations to skip before starting to return results
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// GetUsersByOrganizationParams defines parameters for GetUsersByOrganization.
type GetUsersByOrganizationParams struct {
	// Limit Number of users to return (pagination)
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of users to skip before starting to return results
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// GetAllPaymentsParams defines parameters for GetAllPayments.
type GetAllPaymentsParams struct {
	Limit  *int `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// GetPaymentsByOrganizationParams defines parameters for GetPaymentsByOrganization.
type GetPaymentsByOrganizationParams struct {
	Limit  *int `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// GetQuestionsQuestionIdResponsesParams defines parameters for GetQuestionsQuestionIdResponses.
type GetQuestionsQuestionIdResponsesParams struct {
	// Limit Number of responses to return (pagination)
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of responses to skip before starting to return results
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListTransactionsParams defines parameters for ListTransactions.
type ListTransactionsParams struct {
	// Limit Number of transactions to return per page.
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of transactions to skip for pagination.
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// GetUsersParams defines parameters for GetUsers.
type GetUsersParams struct {
	// Limit Number of users to return (pagination)
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of users to skip before starting to return results
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// GetUserByEmailParams defines parameters for GetUserByEmail.
type GetUserByEmailParams struct {
	Email openapi_types.Email `form:"email" json:"email"`
}

// UpdateUserPasswordJSONBody defines parameters for UpdateUserPassword.
type UpdateUserPasswordJSONBody struct {
	// NewPassword The new password to set.
	NewPassword string `json:"new_password"`

	// OldPassword The current password of the user.
	OldPassword string `json:"old_password"`
}

// LoginUserJSONRequestBody defines body for LoginUser for application/json ContentType.
type LoginUserJSONRequestBody = LoginRequest

// SuperuserLoginJSONRequestBody defines body for SuperuserLogin for application/json ContentType.
type SuperuserLoginJSONRequestBody = LoginRequest

// CreateBalanceJSONRequestBody defines body for CreateBalance for application/json ContentType.
type CreateBalanceJSONRequestBody = CreateBalanceRequest

// UpdateBalanceJSONRequestBody defines body for UpdateBalance for application/json ContentType.
type UpdateBalanceJSONRequestBody = UpdateBalanceRequest

// CreateCampaignJSONRequestBody defines body for CreateCampaign for application/json ContentType.
type CreateCampaignJSONRequestBody = Campaign

// PostCampaignsCampaignIdQuestionsJSONRequestBody defines body for PostCampaignsCampaignIdQuestions for application/json ContentType.
type PostCampaignsCampaignIdQuestionsJSONRequestBody = PostCampaignsCampaignIdQuestionsJSONBody

// UpdateCampaignJSONRequestBody defines body for UpdateCampaign for application/json ContentType.
type UpdateCampaignJSONRequestBody = Campaign

// CreateCustomerJSONRequestBody defines body for CreateCustomer for application/json ContentType.
type CreateCustomerJSONRequestBody = Customer

// UpdateCustomerJSONRequestBody defines body for UpdateCustomer for application/json ContentType.
type UpdateCustomerJSONRequestBody = Customer

// PostFlutterwaveWebhookJSONRequestBody defines body for PostFlutterwaveWebhook for application/json ContentType.
type PostFlutterwaveWebhookJSONRequestBody PostFlutterwaveWebhookJSONBody

// CreateOrganizationJSONRequestBody defines body for CreateOrganization for application/json ContentType.
type CreateOrganizationJSONRequestBody = Organization

// UpdateOrganizationJSONRequestBody defines body for UpdateOrganization for application/json ContentType.
type UpdateOrganizationJSONRequestBody = Organization

// CreatePaymentJSONRequestBody defines body for CreatePayment for application/json ContentType.
type CreatePaymentJSONRequestBody = Payment

// UpdatePaymentByIdJSONRequestBody defines body for UpdatePaymentById for application/json ContentType.
type UpdatePaymentByIdJSONRequestBody = Payment

// PostQuestionsQuestionIdResponsesJSONRequestBody defines body for PostQuestionsQuestionIdResponses for application/json ContentType.
type PostQuestionsQuestionIdResponsesJSONRequestBody = Response

// CreateTransactionJSONRequestBody defines body for CreateTransaction for application/json ContentType.
type CreateTransactionJSONRequestBody = TransactionInput

// UpdateTransactionStatusJSONRequestBody defines body for UpdateTransactionStatus for application/json ContentType.
type UpdateTransactionStatusJSONRequestBody = TransactionStatusUpdate

// CreateUserJSONRequestBody defines body for CreateUser for application/json ContentType.
type CreateUserJSONRequestBody = CreateUserRequestBody

// UpdateUserJSONRequestBody defines body for UpdateUser for application/json ContentType.
type UpdateUserJSONRequestBody = User

// UpdateUserPasswordJSONRequestBody defines body for UpdateUserPassword for application/json ContentType.
type UpdateUserPasswordJSONRequestBody UpdateUserPasswordJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// User login
	// (POST /auth/login)
	LoginUser(c *fiber.Ctx) error
	// User logout
	// (POST /auth/logout)
	LogoutUser(c *fiber.Ctx) error
	// Superuser login
	// (POST /auth/superuser/login)
	SuperuserLogin(c *fiber.Ctx) error
	// Get all balances
	// (GET /balances)
	GetAllBalances(c *fiber.Ctx, params GetAllBalancesParams) error
	// Create a new balance
	// (POST /balances)
	CreateBalance(c *fiber.Ctx) error
	// Get balance by campaign
	// (GET /balances/{campaignId})
	GetBalanceByCampaign(c *fiber.Ctx, campaignId openapi_types.UUID) error
	// Update balance by campaign
	// (PATCH /balances/{campaignId})
	UpdateBalance(c *fiber.Ctx, campaignId openapi_types.UUID) error
	// Get all campaigns
	// (GET /campaigns)
	GetAllCampaigns(c *fiber.Ctx, params GetAllCampaignsParams) error
	// Create a new campaign
	// (POST /campaigns)
	CreateCampaign(c *fiber.Ctx) error
	// Get all campaigns for a specific organization
	// (GET /campaigns/organization)
	GetCampaignsByOrganization(c *fiber.Ctx, params GetCampaignsByOrganizationParams) error
	// Get all questions for a campaign
	// (GET /campaigns/{campaignId}/questions)
	GetCampaignsCampaignIdQuestions(c *fiber.Ctx, campaignId openapi_types.UUID, params GetCampaignsCampaignIdQuestionsParams) error
	// Create a new question for a campaign
	// (POST /campaigns/{campaignId}/questions)
	PostCampaignsCampaignIdQuestions(c *fiber.Ctx, campaignId openapi_types.UUID) error
	// Delete a campaign by ID
	// (DELETE /campaigns/{id})
	DeleteCampaign(c *fiber.Ctx, id openapi_types.UUID) error
	// Get a campaign by ID
	// (GET /campaigns/{id})
	GetCampaignById(c *fiber.Ctx, id openapi_types.UUID) error
	// Update a campaign by ID
	// (PUT /campaigns/{id})
	UpdateCampaign(c *fiber.Ctx, id openapi_types.UUID) error
	// Get all coupons for a specific campaign
	// (GET /campaigns/{id}/coupons)
	GetCouponsByCampaign(c *fiber.Ctx, id openapi_types.UUID) error
	// Generate tokens for a campaign
	// (POST /campaigns/{id}/generate-tokens)
	GenerateTokens(c *fiber.Ctx, id openapi_types.UUID) error
	// Get all customers
	// (GET /customers)
	GetAllCustomers(c *fiber.Ctx, params GetAllCustomersParams) error
	// Create a new customer
	// (POST /customers)
	CreateCustomer(c *fiber.Ctx) error
	// Get all customers for a specific organization
	// (GET /customers/organization)
	GetCustomersByOrganization(c *fiber.Ctx, params GetCustomersByOrganizationParams) error
	// Delete a customer by ID
	// (DELETE /customers/{id})
	DeleteCustomer(c *fiber.Ctx, id openapi_types.UUID) error
	// Get a customer by ID
	// (GET /customers/{id})
	GetCustomerById(c *fiber.Ctx, id openapi_types.UUID) error
	// Update a customer by ID
	// (PUT /customers/{id})
	UpdateCustomer(c *fiber.Ctx, id openapi_types.UUID) error
	// Handle Flutterwave payment notifications
	// (POST /flutterwave/webhook)
	PostFlutterwaveWebhook(c *fiber.Ctx) error
	// Get all organizations
	// (GET /organizations)
	GetOrganizations(c *fiber.Ctx, params GetOrganizationsParams) error
	// Create an organization
	// (POST /organizations)
	CreateOrganization(c *fiber.Ctx) error
	// Get an organization by name
	// (GET /organizations/search)
	GetOrganizationByName(c *fiber.Ctx, params GetOrganizationByNameParams) error
	// Delete an organization
	// (DELETE /organizations/{organization_id})
	DeleteOrganization(c *fiber.Ctx, organizationId openapi_types.UUID) error
	// Get an organization by ID
	// (GET /organizations/{organization_id})
	GetOrganizationById(c *fiber.Ctx, organizationId openapi_types.UUID) error
	// Update an organization
	// (PUT /organizations/{organization_id})
	UpdateOrganization(c *fiber.Ctx, organizationId openapi_types.UUID) error
	// Get all users in an organization
	// (GET /organizations/{organization_id}/users)
	GetUsersByOrganization(c *fiber.Ctx, organizationId openapi_types.UUID, params GetUsersByOrganizationParams) error
	// Get all payments
	// (GET /payments)
	GetAllPayments(c *fiber.Ctx, params GetAllPaymentsParams) error
	// Create a new payment
	// (POST /payments)
	CreatePayment(c *fiber.Ctx) error
	// Get payments by organization ID
	// (GET /payments/organization/{organization_id})
	GetPaymentsByOrganization(c *fiber.Ctx, organizationId openapi_types.UUID, params GetPaymentsByOrganizationParams) error
	// Get a payment by ID
	// (GET /payments/{id})
	GetPaymentById(c *fiber.Ctx, id openapi_types.UUID) error
	// Update a payment by ID
	// (PUT /payments/{id})
	UpdatePaymentById(c *fiber.Ctx, id openapi_types.UUID) error
	// Delete a question
	// (DELETE /questions/{questionId})
	DeleteQuestionsQuestionId(c *fiber.Ctx, questionId openapi_types.UUID) error
	// Get all responses for a question
	// (GET /questions/{questionId}/responses)
	GetQuestionsQuestionIdResponses(c *fiber.Ctx, questionId openapi_types.UUID, params GetQuestionsQuestionIdResponsesParams) error
	// Create a response for a question
	// (POST /questions/{questionId}/responses)
	PostQuestionsQuestionIdResponses(c *fiber.Ctx, questionId openapi_types.UUID) error
	// Get all transactions
	// (GET /transactions)
	ListTransactions(c *fiber.Ctx, params ListTransactionsParams) error
	// Create a new transaction
	// (POST /transactions)
	CreateTransaction(c *fiber.Ctx) error
	// Get a transaction by ID
	// (GET /transactions/{transactionId})
	GetTransaction(c *fiber.Ctx, transactionId openapi_types.UUID) error
	// Update transaction status
	// (PATCH /transactions/{transactionId})
	UpdateTransactionStatus(c *fiber.Ctx, transactionId openapi_types.UUID) error
	// Get all users
	// (GET /users)
	GetUsers(c *fiber.Ctx, params GetUsersParams) error
	// Create a user
	// (POST /users)
	CreateUser(c *fiber.Ctx) error
	// Get a user by email
	// (GET /users/email)
	GetUserByEmail(c *fiber.Ctx, params GetUserByEmailParams) error
	// Delete a user
	// (DELETE /users/{user_id})
	DeleteUser(c *fiber.Ctx, userId openapi_types.UUID) error
	// Get a user by ID
	// (GET /users/{user_id})
	GetUserById(c *fiber.Ctx, userId openapi_types.UUID) error
	// Update a user
	// (PUT /users/{user_id})
	UpdateUser(c *fiber.Ctx, userId openapi_types.UUID) error
	// Update user password
	// (PUT /users/{user_id}/password)
	UpdateUserPassword(c *fiber.Ctx, userId openapi_types.UUID) error
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

type MiddlewareFunc fiber.Handler

// LoginUser operation middleware
func (siw *ServerInterfaceWrapper) LoginUser(c *fiber.Ctx) error {

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.LoginUser(c)
}

// LogoutUser operation middleware
func (siw *ServerInterfaceWrapper) LogoutUser(c *fiber.Ctx) error {

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.LogoutUser(c)
}

// SuperuserLogin operation middleware
func (siw *ServerInterfaceWrapper) SuperuserLogin(c *fiber.Ctx) error {

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.SuperuserLogin(c)
}

// GetAllBalances operation middleware
func (siw *ServerInterfaceWrapper) GetAllBalances(c *fiber.Ctx) error {

	var err error

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAllBalancesParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", query, &params.Limit)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter limit: %w", err).Error())
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", query, &params.Offset)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter offset: %w", err).Error())
	}

	return siw.Handler.GetAllBalances(c, params)
}

// CreateBalance operation middleware
func (siw *ServerInterfaceWrapper) CreateBalance(c *fiber.Ctx) error {

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.CreateBalance(c)
}

// GetBalanceByCampaign operation middleware
func (siw *ServerInterfaceWrapper) GetBalanceByCampaign(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "campaignId" -------------
	var campaignId openapi_types.UUID

	err = runtime.BindStyledParameter("simple", false, "campaignId", c.Params("campaignId"), &campaignId)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter campaignId: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.GetBalanceByCampaign(c, campaignId)
}

// UpdateBalance operation middleware
func (siw *ServerInterfaceWrapper) UpdateBalance(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "campaignId" -------------
	var campaignId openapi_types.UUID

	err = runtime.BindStyledParameter("simple", false, "campaignId", c.Params("campaignId"), &campaignId)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter campaignId: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.UpdateBalance(c, campaignId)
}

// GetAllCampaigns operation middleware
func (siw *ServerInterfaceWrapper) GetAllCampaigns(c *fiber.Ctx) error {

	var err error

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAllCampaignsParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", query, &params.Limit)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter limit: %w", err).Error())
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", query, &params.Offset)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter offset: %w", err).Error())
	}

	return siw.Handler.GetAllCampaigns(c, params)
}

// CreateCampaign operation middleware
func (siw *ServerInterfaceWrapper) CreateCampaign(c *fiber.Ctx) error {

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.CreateCampaign(c)
}

// GetCampaignsByOrganization operation middleware
func (siw *ServerInterfaceWrapper) GetCampaignsByOrganization(c *fiber.Ctx) error {

	var err error

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetCampaignsByOrganizationParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", query, &params.Limit)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter limit: %w", err).Error())
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", query, &params.Offset)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter offset: %w", err).Error())
	}

	// ------------- Required query parameter "organizationId" -------------

	if paramValue := c.Query("organizationId"); paramValue != "" {

	} else {
		err = fmt.Errorf("Query argument organizationId is required, but not found")
		c.Status(fiber.StatusBadRequest).JSON(err)
		return err
	}

	err = runtime.BindQueryParameter("form", true, true, "organizationId", query, &params.OrganizationId)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter organizationId: %w", err).Error())
	}

	return siw.Handler.GetCampaignsByOrganization(c, params)
}

// GetCampaignsCampaignIdQuestions operation middleware
func (siw *ServerInterfaceWrapper) GetCampaignsCampaignIdQuestions(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "campaignId" -------------
	var campaignId openapi_types.UUID

	err = runtime.BindStyledParameter("simple", false, "campaignId", c.Params("campaignId"), &campaignId)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter campaignId: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetCampaignsCampaignIdQuestionsParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", query, &params.Limit)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter limit: %w", err).Error())
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", query, &params.Offset)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter offset: %w", err).Error())
	}

	return siw.Handler.GetCampaignsCampaignIdQuestions(c, campaignId, params)
}

// PostCampaignsCampaignIdQuestions operation middleware
func (siw *ServerInterfaceWrapper) PostCampaignsCampaignIdQuestions(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "campaignId" -------------
	var campaignId openapi_types.UUID

	err = runtime.BindStyledParameter("simple", false, "campaignId", c.Params("campaignId"), &campaignId)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter campaignId: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.PostCampaignsCampaignIdQuestions(c, campaignId)
}

// DeleteCampaign operation middleware
func (siw *ServerInterfaceWrapper) DeleteCampaign(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameter("simple", false, "id", c.Params("id"), &id)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.DeleteCampaign(c, id)
}

// GetCampaignById operation middleware
func (siw *ServerInterfaceWrapper) GetCampaignById(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameter("simple", false, "id", c.Params("id"), &id)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.GetCampaignById(c, id)
}

// UpdateCampaign operation middleware
func (siw *ServerInterfaceWrapper) UpdateCampaign(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameter("simple", false, "id", c.Params("id"), &id)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.UpdateCampaign(c, id)
}

// GetCouponsByCampaign operation middleware
func (siw *ServerInterfaceWrapper) GetCouponsByCampaign(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameter("simple", false, "id", c.Params("id"), &id)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.GetCouponsByCampaign(c, id)
}

// GenerateTokens operation middleware
func (siw *ServerInterfaceWrapper) GenerateTokens(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameter("simple", false, "id", c.Params("id"), &id)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.GenerateTokens(c, id)
}

// GetAllCustomers operation middleware
func (siw *ServerInterfaceWrapper) GetAllCustomers(c *fiber.Ctx) error {

	var err error

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAllCustomersParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", query, &params.Limit)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter limit: %w", err).Error())
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", query, &params.Offset)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter offset: %w", err).Error())
	}

	return siw.Handler.GetAllCustomers(c, params)
}

// CreateCustomer operation middleware
func (siw *ServerInterfaceWrapper) CreateCustomer(c *fiber.Ctx) error {

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.CreateCustomer(c)
}

// GetCustomersByOrganization operation middleware
func (siw *ServerInterfaceWrapper) GetCustomersByOrganization(c *fiber.Ctx) error {

	var err error

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetCustomersByOrganizationParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Required query parameter "organizationId" -------------

	if paramValue := c.Query("organizationId"); paramValue != "" {

	} else {
		err = fmt.Errorf("Query argument organizationId is required, but not found")
		c.Status(fiber.StatusBadRequest).JSON(err)
		return err
	}

	err = runtime.BindQueryParameter("form", true, true, "organizationId", query, &params.OrganizationId)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter organizationId: %w", err).Error())
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", query, &params.Limit)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter limit: %w", err).Error())
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", query, &params.Offset)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter offset: %w", err).Error())
	}

	return siw.Handler.GetCustomersByOrganization(c, params)
}

// DeleteCustomer operation middleware
func (siw *ServerInterfaceWrapper) DeleteCustomer(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameter("simple", false, "id", c.Params("id"), &id)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.DeleteCustomer(c, id)
}

// GetCustomerById operation middleware
func (siw *ServerInterfaceWrapper) GetCustomerById(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameter("simple", false, "id", c.Params("id"), &id)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.GetCustomerById(c, id)
}

// UpdateCustomer operation middleware
func (siw *ServerInterfaceWrapper) UpdateCustomer(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameter("simple", false, "id", c.Params("id"), &id)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.UpdateCustomer(c, id)
}

// PostFlutterwaveWebhook operation middleware
func (siw *ServerInterfaceWrapper) PostFlutterwaveWebhook(c *fiber.Ctx) error {

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.PostFlutterwaveWebhook(c)
}

// GetOrganizations operation middleware
func (siw *ServerInterfaceWrapper) GetOrganizations(c *fiber.Ctx) error {

	var err error

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetOrganizationsParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", query, &params.Limit)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter limit: %w", err).Error())
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", query, &params.Offset)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter offset: %w", err).Error())
	}

	return siw.Handler.GetOrganizations(c, params)
}

// CreateOrganization operation middleware
func (siw *ServerInterfaceWrapper) CreateOrganization(c *fiber.Ctx) error {

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.CreateOrganization(c)
}

// GetOrganizationByName operation middleware
func (siw *ServerInterfaceWrapper) GetOrganizationByName(c *fiber.Ctx) error {

	var err error

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetOrganizationByNameParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Required query parameter "name" -------------

	if paramValue := c.Query("name"); paramValue != "" {

	} else {
		err = fmt.Errorf("Query argument name is required, but not found")
		c.Status(fiber.StatusBadRequest).JSON(err)
		return err
	}

	err = runtime.BindQueryParameter("form", true, true, "name", query, &params.Name)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter name: %w", err).Error())
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", query, &params.Limit)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter limit: %w", err).Error())
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", query, &params.Offset)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter offset: %w", err).Error())
	}

	return siw.Handler.GetOrganizationByName(c, params)
}

// DeleteOrganization operation middleware
func (siw *ServerInterfaceWrapper) DeleteOrganization(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "organization_id" -------------
	var organizationId openapi_types.UUID

	err = runtime.BindStyledParameter("simple", false, "organization_id", c.Params("organization_id"), &organizationId)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter organization_id: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.DeleteOrganization(c, organizationId)
}

// GetOrganizationById operation middleware
func (siw *ServerInterfaceWrapper) GetOrganizationById(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "organization_id" -------------
	var organizationId openapi_types.UUID

	err = runtime.BindStyledParameter("simple", false, "organization_id", c.Params("organization_id"), &organizationId)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter organization_id: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.GetOrganizationById(c, organizationId)
}

// UpdateOrganization operation middleware
func (siw *ServerInterfaceWrapper) UpdateOrganization(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "organization_id" -------------
	var organizationId openapi_types.UUID

	err = runtime.BindStyledParameter("simple", false, "organization_id", c.Params("organization_id"), &organizationId)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter organization_id: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.UpdateOrganization(c, organizationId)
}

// GetUsersByOrganization operation middleware
func (siw *ServerInterfaceWrapper) GetUsersByOrganization(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "organization_id" -------------
	var organizationId openapi_types.UUID

	err = runtime.BindStyledParameter("simple", false, "organization_id", c.Params("organization_id"), &organizationId)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter organization_id: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetUsersByOrganizationParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", query, &params.Limit)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter limit: %w", err).Error())
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", query, &params.Offset)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter offset: %w", err).Error())
	}

	return siw.Handler.GetUsersByOrganization(c, organizationId, params)
}

// GetAllPayments operation middleware
func (siw *ServerInterfaceWrapper) GetAllPayments(c *fiber.Ctx) error {

	var err error

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAllPaymentsParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", query, &params.Limit)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter limit: %w", err).Error())
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", query, &params.Offset)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter offset: %w", err).Error())
	}

	return siw.Handler.GetAllPayments(c, params)
}

// CreatePayment operation middleware
func (siw *ServerInterfaceWrapper) CreatePayment(c *fiber.Ctx) error {

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.CreatePayment(c)
}

// GetPaymentsByOrganization operation middleware
func (siw *ServerInterfaceWrapper) GetPaymentsByOrganization(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "organization_id" -------------
	var organizationId openapi_types.UUID

	err = runtime.BindStyledParameter("simple", false, "organization_id", c.Params("organization_id"), &organizationId)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter organization_id: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetPaymentsByOrganizationParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", query, &params.Limit)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter limit: %w", err).Error())
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", query, &params.Offset)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter offset: %w", err).Error())
	}

	return siw.Handler.GetPaymentsByOrganization(c, organizationId, params)
}

// GetPaymentById operation middleware
func (siw *ServerInterfaceWrapper) GetPaymentById(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameter("simple", false, "id", c.Params("id"), &id)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.GetPaymentById(c, id)
}

// UpdatePaymentById operation middleware
func (siw *ServerInterfaceWrapper) UpdatePaymentById(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameter("simple", false, "id", c.Params("id"), &id)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.UpdatePaymentById(c, id)
}

// DeleteQuestionsQuestionId operation middleware
func (siw *ServerInterfaceWrapper) DeleteQuestionsQuestionId(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "questionId" -------------
	var questionId openapi_types.UUID

	err = runtime.BindStyledParameter("simple", false, "questionId", c.Params("questionId"), &questionId)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter questionId: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.DeleteQuestionsQuestionId(c, questionId)
}

// GetQuestionsQuestionIdResponses operation middleware
func (siw *ServerInterfaceWrapper) GetQuestionsQuestionIdResponses(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "questionId" -------------
	var questionId openapi_types.UUID

	err = runtime.BindStyledParameter("simple", false, "questionId", c.Params("questionId"), &questionId)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter questionId: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetQuestionsQuestionIdResponsesParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", query, &params.Limit)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter limit: %w", err).Error())
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", query, &params.Offset)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter offset: %w", err).Error())
	}

	return siw.Handler.GetQuestionsQuestionIdResponses(c, questionId, params)
}

// PostQuestionsQuestionIdResponses operation middleware
func (siw *ServerInterfaceWrapper) PostQuestionsQuestionIdResponses(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "questionId" -------------
	var questionId openapi_types.UUID

	err = runtime.BindStyledParameter("simple", false, "questionId", c.Params("questionId"), &questionId)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter questionId: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.PostQuestionsQuestionIdResponses(c, questionId)
}

// ListTransactions operation middleware
func (siw *ServerInterfaceWrapper) ListTransactions(c *fiber.Ctx) error {

	var err error

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params ListTransactionsParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", query, &params.Limit)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter limit: %w", err).Error())
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", query, &params.Offset)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter offset: %w", err).Error())
	}

	return siw.Handler.ListTransactions(c, params)
}

// CreateTransaction operation middleware
func (siw *ServerInterfaceWrapper) CreateTransaction(c *fiber.Ctx) error {

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.CreateTransaction(c)
}

// GetTransaction operation middleware
func (siw *ServerInterfaceWrapper) GetTransaction(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "transactionId" -------------
	var transactionId openapi_types.UUID

	err = runtime.BindStyledParameter("simple", false, "transactionId", c.Params("transactionId"), &transactionId)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter transactionId: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.GetTransaction(c, transactionId)
}

// UpdateTransactionStatus operation middleware
func (siw *ServerInterfaceWrapper) UpdateTransactionStatus(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "transactionId" -------------
	var transactionId openapi_types.UUID

	err = runtime.BindStyledParameter("simple", false, "transactionId", c.Params("transactionId"), &transactionId)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter transactionId: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.UpdateTransactionStatus(c, transactionId)
}

// GetUsers operation middleware
func (siw *ServerInterfaceWrapper) GetUsers(c *fiber.Ctx) error {

	var err error

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetUsersParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", query, &params.Limit)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter limit: %w", err).Error())
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", query, &params.Offset)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter offset: %w", err).Error())
	}

	return siw.Handler.GetUsers(c, params)
}

// CreateUser operation middleware
func (siw *ServerInterfaceWrapper) CreateUser(c *fiber.Ctx) error {

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.CreateUser(c)
}

// GetUserByEmail operation middleware
func (siw *ServerInterfaceWrapper) GetUserByEmail(c *fiber.Ctx) error {

	var err error

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetUserByEmailParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Required query parameter "email" -------------

	if paramValue := c.Query("email"); paramValue != "" {

	} else {
		err = fmt.Errorf("Query argument email is required, but not found")
		c.Status(fiber.StatusBadRequest).JSON(err)
		return err
	}

	err = runtime.BindQueryParameter("form", true, true, "email", query, &params.Email)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter email: %w", err).Error())
	}

	return siw.Handler.GetUserByEmail(c, params)
}

// DeleteUser operation middleware
func (siw *ServerInterfaceWrapper) DeleteUser(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "user_id" -------------
	var userId openapi_types.UUID

	err = runtime.BindStyledParameter("simple", false, "user_id", c.Params("user_id"), &userId)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter user_id: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.DeleteUser(c, userId)
}

// GetUserById operation middleware
func (siw *ServerInterfaceWrapper) GetUserById(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "user_id" -------------
	var userId openapi_types.UUID

	err = runtime.BindStyledParameter("simple", false, "user_id", c.Params("user_id"), &userId)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter user_id: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.GetUserById(c, userId)
}

// UpdateUser operation middleware
func (siw *ServerInterfaceWrapper) UpdateUser(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "user_id" -------------
	var userId openapi_types.UUID

	err = runtime.BindStyledParameter("simple", false, "user_id", c.Params("user_id"), &userId)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter user_id: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.UpdateUser(c, userId)
}

// UpdateUserPassword operation middleware
func (siw *ServerInterfaceWrapper) UpdateUserPassword(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "user_id" -------------
	var userId openapi_types.UUID

	err = runtime.BindStyledParameter("simple", false, "user_id", c.Params("user_id"), &userId)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter user_id: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.UpdateUserPassword(c, userId)
}

// FiberServerOptions provides options for the Fiber server.
type FiberServerOptions struct {
	BaseURL     string
	Middlewares []MiddlewareFunc
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router fiber.Router, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, FiberServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router fiber.Router, si ServerInterface, options FiberServerOptions) {
	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	for _, m := range options.Middlewares {
		router.Use(m)
	}

	router.Post(options.BaseURL+"/auth/login", wrapper.LoginUser)

	router.Post(options.BaseURL+"/auth/logout", wrapper.LogoutUser)

	router.Post(options.BaseURL+"/auth/superuser/login", wrapper.SuperuserLogin)

	router.Get(options.BaseURL+"/balances", wrapper.GetAllBalances)

	router.Post(options.BaseURL+"/balances", wrapper.CreateBalance)

	router.Get(options.BaseURL+"/balances/:campaignId", wrapper.GetBalanceByCampaign)

	router.Patch(options.BaseURL+"/balances/:campaignId", wrapper.UpdateBalance)

	router.Get(options.BaseURL+"/campaigns", wrapper.GetAllCampaigns)

	router.Post(options.BaseURL+"/campaigns", wrapper.CreateCampaign)

	router.Get(options.BaseURL+"/campaigns/organization", wrapper.GetCampaignsByOrganization)

	router.Get(options.BaseURL+"/campaigns/:campaignId/questions", wrapper.GetCampaignsCampaignIdQuestions)

	router.Post(options.BaseURL+"/campaigns/:campaignId/questions", wrapper.PostCampaignsCampaignIdQuestions)

	router.Delete(options.BaseURL+"/campaigns/:id", wrapper.DeleteCampaign)

	router.Get(options.BaseURL+"/campaigns/:id", wrapper.GetCampaignById)

	router.Put(options.BaseURL+"/campaigns/:id", wrapper.UpdateCampaign)

	router.Get(options.BaseURL+"/campaigns/:id/coupons", wrapper.GetCouponsByCampaign)

	router.Post(options.BaseURL+"/campaigns/:id/generate-tokens", wrapper.GenerateTokens)

	router.Get(options.BaseURL+"/customers", wrapper.GetAllCustomers)

	router.Post(options.BaseURL+"/customers", wrapper.CreateCustomer)

	router.Get(options.BaseURL+"/customers/organization", wrapper.GetCustomersByOrganization)

	router.Delete(options.BaseURL+"/customers/:id", wrapper.DeleteCustomer)

	router.Get(options.BaseURL+"/customers/:id", wrapper.GetCustomerById)

	router.Put(options.BaseURL+"/customers/:id", wrapper.UpdateCustomer)

	router.Post(options.BaseURL+"/flutterwave/webhook", wrapper.PostFlutterwaveWebhook)

	router.Get(options.BaseURL+"/organizations", wrapper.GetOrganizations)

	router.Post(options.BaseURL+"/organizations", wrapper.CreateOrganization)

	router.Get(options.BaseURL+"/organizations/search", wrapper.GetOrganizationByName)

	router.Delete(options.BaseURL+"/organizations/:organization_id", wrapper.DeleteOrganization)

	router.Get(options.BaseURL+"/organizations/:organization_id", wrapper.GetOrganizationById)

	router.Put(options.BaseURL+"/organizations/:organization_id", wrapper.UpdateOrganization)

	router.Get(options.BaseURL+"/organizations/:organization_id/users", wrapper.GetUsersByOrganization)

	router.Get(options.BaseURL+"/payments", wrapper.GetAllPayments)

	router.Post(options.BaseURL+"/payments", wrapper.CreatePayment)

	router.Get(options.BaseURL+"/payments/organization/:organization_id", wrapper.GetPaymentsByOrganization)

	router.Get(options.BaseURL+"/payments/:id", wrapper.GetPaymentById)

	router.Put(options.BaseURL+"/payments/:id", wrapper.UpdatePaymentById)

	router.Delete(options.BaseURL+"/questions/:questionId", wrapper.DeleteQuestionsQuestionId)

	router.Get(options.BaseURL+"/questions/:questionId/responses", wrapper.GetQuestionsQuestionIdResponses)

	router.Post(options.BaseURL+"/questions/:questionId/responses", wrapper.PostQuestionsQuestionIdResponses)

	router.Get(options.BaseURL+"/transactions", wrapper.ListTransactions)

	router.Post(options.BaseURL+"/transactions", wrapper.CreateTransaction)

	router.Get(options.BaseURL+"/transactions/:transactionId", wrapper.GetTransaction)

	router.Patch(options.BaseURL+"/transactions/:transactionId", wrapper.UpdateTransactionStatus)

	router.Get(options.BaseURL+"/users", wrapper.GetUsers)

	router.Post(options.BaseURL+"/users", wrapper.CreateUser)

	router.Get(options.BaseURL+"/users/email", wrapper.GetUserByEmail)

	router.Delete(options.BaseURL+"/users/:user_id", wrapper.DeleteUser)

	router.Get(options.BaseURL+"/users/:user_id", wrapper.GetUserById)

	router.Put(options.BaseURL+"/users/:user_id", wrapper.UpdateUser)

	router.Put(options.BaseURL+"/users/:user_id/password", wrapper.UpdateUserPassword)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xdX3PbtrL/Kjy896GZK1myLDu2n26cnva606Zu4kzvnE4mA5EriQ0JqCBoV834u58h",
	"QIAACf6TRMrNyUsbi+AC2P3tYnexAD+7Hok2BANmsXv92aUQbwiOgf9xg/y38EcCMfsnpYSmP3kEM8As",
	"/SfabMLAQywgePJ7THD6W+ytIULpv/6bwtK9dv9rktOfiKfxRFB7enoauT7EHg02KRH32r3FDygMfCfA",
	"m4S5TyP3FjOgGIXvgD4AHWgUojMHxPOR+4aw70iC/f57fgsxSagHDibMWfI+00bZe0IkIcIepP/cULIB",
	"ygIhKxSRRIxrSWiEmHvtLkOCmDty2XYD7rWLk2gBfEIeijYoWOFb32ifJIGfN48ZDfAqbR60axYzRFmA",
	"V9oQm4byNHIp/JEEFHz3+jeX09UGV6Y5kvP8oGiRxe/gcbC8zt6sYw78iaJNCO716XR6cj7qwKw3KAKD",
	"gvsuiSKgzh0lEbExxFsjijwG9J4/0V99FW7WCCcR0MCzvkqSDcnk0/WtHwGv2LowWdU6wAxW2cx48zdi",
	"pgXeWNtTQAz8VyYj3dl0dj6eno2n8/vT2fXZ/Pr84l+uxlkfMRizIEqlh5MwRIv0NUYTqMRaTvz8fAqX",
	"8+l0DLOrxXh+6s/H6OXpxXg+v7g4P5/Pp9PpVO+sCpyErhAO/uLaWmSrf3EGc292OV5e+rPx3Du7Gi/O",
	"Fovx1czzzxdXV5dodtqmjw0NPNgNZNzIBlZhnNtEETPEkticBvJY8AC2gT1C6JEIfoI4RqsCEn8VzxxG",
	"HJJQJxaYlqD/R5lcnc5yHdHQW9SBAkQLECwNtMQXpf6S2YoTJQlbDQTvrWweTHt4eGB4xC/q/+nN7PXZ",
	"t3N3QBWg4ANEYFJfojDO9XBBSAgI66171PZG68/5pg3cKlNulLL1IfNWBl0d91/29ljx+OTfx0Czmd8Q",
	"f2uZve9TiPk/LdjEy4BGdyiOHwk1p7yRP1qmDREKQqO1+MXSdBnQmMnls/Q0RDUPdaX+2NIP2XSdymZN",
	"MOSWt6w4JLSNriDFfJbanEaKK3onIyWRjHh5oiN9xEUZWaGQxIxEYgaHd36KljH6hK4ut/7FeL1+ORt/",
	"+v3yYjfLqFCUk/6drPGJT+B/s59OPBLppKphBuAvkPfJJPd9qiJODPQh8OAfjfDMX/yBrPGQ5lnXg5z6",
	"t8S6omNgj4QWpvrT/ZujuT4puk3S/3M6O5ufX7y8vJpWmM3WHoxtoahQNzGQXO0UKHKeaU5ElfNgAN+m",
	"bSoSNVWNh4wf5XJfmnOUO2D1M4yUA6RRtI3jR7IKcOWq18FGdzSahfEqI1dnoX7WeNx1jYo2CG8/4qpl",
	"QjaIg7/0Bkasgxny2McN0JjgOkpGO4Xrfda/lutWgP0kZnTbDA/+vuzONrOKeejrjuqtwL0Ct22CvEPb",
	"KMuBHH6l+Vi0rzP/Yjm7Op+Nr9D5Yjy/uDgbX53C6fjipX/+8gydLa/mrexryW57MzT3r+bj2cvl5Xi+",
	"XPjjy+XL+fjS9y+9l94lzK+8rpHlx74WB81a4iRKMbAB7KcPhbxCYMCtIgpC4SjnY8hblsgyinCcWl3b",
	"0OeZ+b44n4v/NlHgGS+dxP3/v1GLQDurXnaDdFxolrvYb2kuimc2BP+ShZVNoeChUmOEJ/h4BwGDyG7l",
	"KqIlRCnaclbDn8z6IpPppQwavOHIjZKQBZsQPnprImJlitLIQuNI60gsI8lfszH0bZY2ttgEHD9W+NVe",
	"5rIeltcyZdCKqm3iGgFjjCM5FxsD7nP0DRp99sNDzb1s4U628w7rAixYAoUseO5k++LE88R6llu+sn78",
	"+ba2g6L+oIDyBMaHzibrtpzCMPBT8jvNqDD3UPUhZ6PQ2dSAwFu+fTIoDEkUBXG2CdKCejfUDgzH5wu4",
	"XbDWCWIKmLlAG7D2jr/xfuMjZrH+LVi5TMI6bhY4ULOoizEcLhNY6LkmDfc+tuZdaiKartmzynilpUFP",
	"I2R81CRbuyRaHtrjPLTHZiYtj2G0/irSaGVppfoNXkIDtn3nrSHKdroBUaCvErFvtuB/fSen9cOv9262",
	"CcuT5PxpPsc1YxuxmRvgJUnfNzd1X93dOktCnQhhtArwytEHGTsI+04SA42dADv/CvzgBnmfAHMmBoz7",
	"0dqvzqu7W3fkPgCNBfXTk+nJVPiYgNEmcK/dM/5Tyh625rOboIStJyFZBcI5IUIxUrAquylSCRzJQiRa",
	"Nvkgm95GquLJFHzq8PIftOKD2XTaqW9T+Rj5BLgsix9+vXcQNzuOaGFBapJpc91kOJ+ensroKhcTKCvn",
	"CAE8jdy5mJqtA8WCSbH4gr932n8NwnucooXQ4C/wnbEjSzI8Cj5gFqAwFkqURBGi2/SFGKic29MoBxvJ",
	"fJAqtJGEKbgdTO6RbY8zl0G4TUe6At9JR2dbbDoKlIg6lWNKJjUtQRynlkVgWrdx7vVvpnX77cPTB5v0",
	"+ESU+OJkAzRVhCar8U425Or91XT0ZDqUPL4YI5LCNsBxslwGXgCYOXwFNy3Lu+KsU3wuhIPHRbUCCyS/",
	"B/YqDG9ks3QdpCgCBjTm2pDCOQ3yee5TOEVuGEQBk4s8EsJfoiRkonYmCnAQpf7rabkY42lkJ0mWyxgq",
	"aOokLaU2qYbuBWiVZKoTntxhfiqmmsri/DGImUOWjuJ9jqNquXezQ98Dc1AYGl3YTY6x49+TxbFWFbSy",
	"PIdTLiWfsjyyR05WkeXE2gKn2YbiS75D5VRayW/kntsIyaJMvquaF0p2kbbgr4McDI9S5KZ6Tz7nse1T",
	"na5nvLjZqvI/u8an3nCunUbgbMpU19im9OG+irqn/CkwGsCDFQEtpDufzm0wEbQLJahd9DiTobPYqkIy",
	"ETMyb12WoRG3Dy68w9sOax6iB69lT+wkfJg92o626OrPyghJ2OGY2hr5V5Mv8Vq1K6HTHLNIs6UrpSLt",
	"MJKqaUKx880mjf858Rd8B7aNH2LU8Db5Ia1GE38KNs4CloSCI6vNtFFSiJOQxRUDtHg1aoTPwqt5rRmc",
	"JrfmlRNmjk2OhJ2cFu31eq9FW6N6cVtyeA/qqpj9mkyWz7o5K4WTIDv7FhUKPyGFYpQq7Veqf7M16le+",
	"GoI9DEFVxFTc3TieX2YvCogPYIV4zbsYgimke8JQ6GCLqJaEOmwNTrwBL1gG4BsZZFer9Ti3crs50/Bj",
	"0Qw29Vm1vL8hBo0E+xmlIC4Q2MvMcqJIDs4rk9Y0XY8jJnJvP26l86/Vm7+o9wb0T2v0WM3jWVgVYzRf",
	"tnuhKoc6uRc5g6ReGetSZ0Uw6aGc2shlaJXi0s0R+6HSJ7kj8bMB+x7B2AEEN5yrlI+jDBj5rMJV2tkJ",
	"knBph5aC+QxE+sWHEMQOv4mhb/nvnXIvwaHXdstCpLxOMW6b11n31o7JD8EMjcVpzHn7bdpf02Jzs731",
	"j8O96bBhgIr6e5EAt5AW9mcFUbbM0+DYPXbcN7DAqxNNPcg/S/mUIVC2ahNx+LTeFRRNOiaXj6yi7SIU",
	"cRa2w+aPZFevqpt6+aKfoo9fFclzUa4Ap5KDMd+ajav3q7/PGt6Ldn8Dae5Vn56zo7ruvCD/FuGiYJ4j",
	"md4ypaPwEcQcItlpry5w6i9VLHEh9vZLfrXAXFZf2ZguVu2+ZomefbpYHpvtli5WEt7NwuWvN6SL5eh6",
	"chvU5AdOFxv9FtQ+e3akdHE+Ml3h26eL5RtN6eKe8591yi2H+DxMjT6ar6am5HMp9rRJyFoU46esMpBX",
	"W8l6QQNmdalcrfdDp3KNidWncpUWtsxF5EbzmeQipEnrlouQb+2di5CEmnMRWcsvIhfRZo1pyEXsKYEs",
	"F1Fif10uYmjsHtupGFjg3XIRe8o/z0UUIJBatWWYMAb0ET3A5BEWa0I+VUetdyRm3+Uv/Jq1312AZlDp",
	"I4bK079D25Ag3+FXCQSYr8X5uS/HB4aCkMc4FQesCt4z/z1dhUj4AKmrxtczjaRru+lMnEcqVhoFfyTG",
	"qylb6+9JK0Sw2quijfMNnKxORhoyRo44lPbCGlj/KY+7VxOmxfN1dQcNRi48gHVfeLuB1BXgj+UovTWi",
	"K341jjj6PxLMWAI9ySfwou0Bhz6r6SP7pXMcwA4FD4IH8Hc7iVGk0i1UyFTH2QiYtyprUy99I52pOFhh",
	"xBIKL3bJTihT8X8I+yE4mo6n44pSiWPCUscIyR05uWWTzV7u2BiHyupClJ+Nhq0zFOahtT1DB6O4/iBx",
	"RGl4h44l9Nr95xVX/FyIA9rGFiZicvTWnyix3ci7UwRQ6r4uEVIIpvvwW0w2DpsQKfdtikx/LhMj+5wB",
	"GkbSMrOCLUGdIf1JDIiK0vA2VutmKy/7as6pZGeHq73kDpmTg5rAv4fVG8zSHUw7pFuaO/X1KFeXe3c3",
	"YiauU+eeM9KC78+Fc+ktshgt0odmNFi+OqnntEaB7bWpjT5kIBMcuJQJa2dEWuY4+uXrf6KWNGZBjo/9",
	"5+BeHAkaWYqkZ2jI3Eizb1CynRN+W0ads/A+brsD0x+MalZtcdvHc/Af1Ei+7J0XceS+fWSkrmNha6iq",
	"e+/NXoZh3r9VPbLEQFMVwp1stuMB+NqPR3Q49K5D4eDiN3NNOmeqn7SCjLzj1HJ+gxGGwubzG7JLiSMf",
	"MbRAMZy4bc5oaN3scqAjL1VQM++1eEbgVu+rLpqXzO1npVWiGzaGN7otZdJ5Kk93ji1hfH2ekifphzqS",
	"v1GT0QyOsTDbY5oqeySN0fEX5f8I43cwE7fPYTJlAPkOfzlK69Maqb4XWzP8kNtvCtOf2yH3S9gSb2Gh",
	"6jfE7/ItiSEqMpmD1C5Im7DxGKI68vI1KDg63RhRtXwdH1hqW76ArdQsqIN1k8/5NdAtsnXq/NQv+uXR",
	"zRA07pruOV+nTpfZc3U71RbJ8dccJbOzdGKMt8r4Wtj6Vr03IH9rQmg1j2cR0Buj+bKDenXlfKfK7ZxB",
	"sqDyj/xA5g4hj0nPqhA5YutP4j4XsPe0ruXyGjYuM/stfW+VPzvkgVs5kXaASC2kVsdUbQ1Tr/peb9i6",
	"ckMnr6n/BqizQSuej+jhSsS2o+FGKmVVbjNPdqvK6NUkFa8IZSh83e4eD2PCLXJBxpdM2kdz+gcodjrU",
	"JcM2o/edbKJJoT4VdG+U//Vhd0rfRRjY/hiCsZyl0woGD3zsnxk9FwzN5LP2V8MVi6aQmhcig/KzDYc7",
	"CEZtl3YPYPUi1TyIrbsJsfRxhWPwvFc9NL4ZMXCc20HqWWGwPezdIeJkJdpCLdvtZ7Zf8L/uL/4d9hf3",
	"2BpsWlR7/IqD/YvDAy+p2RXq5VvH4/zc6O7lkTutt4m81V1o80R94KVOp2+2/1QfzmzcoZWfP2lh2Cu+",
	"JdPralorkwHLjbgk0pVWMEETyef0f+2K7zIFal51M5L9J+8yNh6tyC4D+KgBzy3Tnv2w7QsGc+Pex/CI",
	"7eHi7Hj4U4O1kh62FK60hiiDNdG/ttUAgrv8m1jPHgxmUgXD40d9ogXHfA1ZZYJowb1KYCf613Prvj9G",
	"Qr+BupdQCpjlPZAlT9akTGrZTfFzfXqfI3OCH57HSTwJF2uUc7LbubwGmi3umJfHHOV3jZYBhH48ch4B",
	"fVLyeXHS7sze2LnFHqEUPOaQ0Ffvn1RuR3LlV3uRJ8OdmMlMAbf6CilPjSSe/h0AAP//Tr1oDcaNAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
